#!/usr/bin/python3

import os
import re
import shutil
import subprocess
import sys
import time
import zipfile
import zlib
from pathlib import Path

ROOT_DIR = os.path.join(os.environ['HOME'], '.dosemu', 'drive_c')

SCRIPT_ROOT = os.path.dirname(os.path.realpath(__file__))

SOURCES = [
    {
        'type': 'windows',
        'name': 'win31',
        'short_name': 'win31',
        'lang': 'en',
        'codepage': 'cp437',
        'urls':
            [
                'http://archive.org/download/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip/IBM%20PC%20Compatibles%20%5BTOSEC%5D%2FIBM%20PC%20Compatibles%20-%20Operating%20Systems%20-%20%5BIMA%5D%20%28TOSEC-v2011-01-06_CM%29%2FMicrosoft%20Windows%20v3.1%20%281992%29%28Microsoft%29%28Disk%201%20of%206%29.zip'
            ]
    },
    {
        'type': 'integratableDriver',
        'name': 'w31drv-i33mouse',
        'short_name': 'mouse',
        'urls':
            [
                'https://raw.githubusercontent.com/dosemu2/win31-mouse-driver/master/out/oemsetup.inf',
                'https://raw.githubusercontent.com/dosemu2/win31-mouse-driver/master/out/i33mouse.drv'
            ]
    },
    {
        'type': 'integratableDriver',
        'needsUnzipping': True,
        'name': 'w31drv-svga',
        'short_name': 'video',
        'urls':
            [
                'https://archive.org/download/SVGA_EXE/SVGA.EXE'
            ]
    }
    ]

SYSLANG = re.findall(r'([a-z][a-z]+)_.+', os.environ['LANG'])[0]
WINLANG = 'en'
WINCODEPAGE = '437'
for source in SOURCES:
    if source.get('lang') == SYSLANG:
        WINLANG = source.get('lang')
        WINCODEPAGE = source.get('codepage')

target = '';
target_dir = '';
for source in SOURCES:
    if source.get('type') == 'windows':
        if source.get('lang') != WINLANG:
            continue
        target = source.get('short_name')
        target_dir = os.path.join(ROOT_DIR, 'inst', target)
        destination_dir = target_dir
    if source.get('type') == 'integratableDriver' or source.get('type') == 'driver':
        destination_dir = os.path.join(ROOT_DIR, 'inst', target + 'drv', source.get('short_name'))

    download_command = [os.path.join(SCRIPT_ROOT, 'dosemu-downloader')]
    download_command.append('-n')
    download_command.append(source.get('name'))
    download_command.append('-d')
    download_command.append(destination_dir)
    download_command.append('-c')
    for url in source.get('urls'):
        download_command.append(url)
    if (subprocess.run(download_command).returncode != 0):
        print('Download error')
        sys.exit(1)

    if source.get('needsUnzipping'):
        for zipfilearchive in Path(destination_dir).glob('*.[zZeE][iIxX][pPeE]'):
            subprocess.run(['unzip', '-n', '-L', zipfilearchive, '-d', destination_dir])
            os.remove(zipfilearchive)

    if source.get('type') == 'integratableDriver':
        patch_command = [os.path.join(SCRIPT_ROOT, 'dosemu-patchwin31inst')]
        patch_command.append('-s')
        patch_command.append(destination_dir)
        patch_command.append('-d')
        patch_command.append(target_dir)
        patch_command.append('-c')
        patch_command.append(WINCODEPAGE)
        if (subprocess.run(patch_command).returncode != 0):
            print('Driver error')
            sys.exit(1)
